baseURL = "https://pengpeng0128.github.io/"
languageCode = "zh-CN"
title = "Pengpeng"
theme = "PaperMod"

# 是否开启 Hugo extended
enableGitInfo = true

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  mainSections = ["posts"]   # 指定博客文章所在 section


[[menu.main]]
  name = "主页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "关于"
  url = "/about/"
  weight = 3
